[default.probe]
protocol = "Swd"

[default.general]
# chip = "nrf52833" # uncomment this line for micro:bit V2
# chip = "nrf51822_xxAA" # uncomment this line for micro:bit V1

[default.rtt]
enabled = true

[default.gdb]
enabled = false
