block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
    "build-book",
    "build-chapter (05-led-roulette)",
    "build-chapter (07-uart)",
    "build-chapter (08-i2c)",
    "build-chapter (15-led-compass)",
    "build-chapter (16-punch-o-meter)",
]
