block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
    "build-book",
    "build-chapter-f3discovery (05-led-roulette)",
    "build-chapter-f3discovery (06-hello-world)",
    "build-chapter-f3discovery (07-registers)",
    "build-chapter-f3discovery (08-leds-again)",
    "build-chapter-f3discovery (09-clocks-and-timers)",
    "build-chapter-f3discovery (11-usart)",
    "build-chapter-f3discovery (14-i2c)",
    "build-chapter-f3discovery (15-led-compass)",
    "build-chapter-f3discovery (16-punch-o-meter)",
    "build-chapter-microbit (05-led-roulette)",
    "build-chapter-microbit (07-uart)",
    "build-chapter-microbit (08-i2c)",
    "build-chapter-microbit (09-led-compass)",
    "build-chapter-microbit (10-punch-o-meter)",
]
