block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
    "build-book",
    "build-chapter-microbit (05-led-roulette)",
    "build-chapter-microbit (07-uart)",
    "build-chapter-old (08-i2c)",
    "build-chapter-old (15-led-compass)",
    "build-chapter-old (16-punch-o-meter)",
]
